server.port: 80

spring.security.oauth2:
  client:
    registration:
      custom:
        client-id: 881ea0651c17428b81d271d1a65ef9ca
        #            client-secret: Set this in environment variables
        scope: user-modify-playback-state
        authorization-grant-type: authorization_code
        redirect-uri: http://localhost:8080/login/oauth2/code/spotify
    provider:
      custom:
        authorization-uri: https://accounts.spotify.com/authorize
        token-uri: https://accounts.spotify.com/api/token
        user-info-uri: https://api.spotify.com/v1/me
        user-name-attribute: display_name

redis:
  hostname: 127.0.0.1
  port: 6379
  username: test
  password: test

logging.level.org.springframework.web: DEBUG