name: Deploy Docker image

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hannesknutsson/caver:$GITHUB_SHA
      - name: Log in to DockerHub
        env:
          DOCKERHUB_AUTH: ${{ secrets.DOCKERHUB_AUTH }}
        run: docker login -u hannesknutsson -p $DOCKERHUB_AUTH
      - name: Push image to DockerHub
        run: docker push hannesknutsson/caver:$GITHUB_SHA

  update-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the build php script
        run: |
          cd charts/caver-backend/ci
          sed -i '/tag:/c\  tag: hannesknutsson/caver:$GITHUB_SHA' dev-values.yaml
          cd -
      - name: Commit files
        run: |
          git config --local user.name "GitHub Actions"
          git add ./charts
          git commit -m "Update dev environment helm chart values"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
