name: Build Docker image

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:
    needs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: caver-jar

      - name: Create artifact target dir
        run: mkdir target

      - name: Move artifact to target dir
        run: mv caver*.jar target/caver.jar

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag caver:$(date +%s)
